name: geo
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.12
  - click
  - dask
  - fiona
  - geopandas
  - gdal
  - h3
  - libpysal
  - matplotlib
  - mgwr
  - minisom
  - numpy
  - pandas
  - psutil
  - psycopg2
  - pyproj
  - pytest
  - numpy
  - PyYAML
  - rasterio
  - rioxarray
  - scikit-learn
  - scipy
  - seaborn
  - Shapely
  - spopt
  - tqdm
  - xarray
  - postgresql
  - postgis
  - pyright
  - affine
  - bokeh
  - bottleneck
  - descartes
  - geopy
  - h5netcdf
  - netcdf4
  - networkx
  - pulp
  - pynio
  - pyqt
  - pysal
  - rtree
  - shapely
  - spglm
  - spreg
  - sqlalchemy
  - statsmodels
  - yaml
