name: geo_py311
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Core Setup ---
  - python=3.11

  # --- Key Packages from Your List (The ones you import in your code) ---
  - geopandas
  - fiona
  - rasterio
  - rasterstats
  - gdal # Good to have explicitly
  - shapely
  - pyproj
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - folium
  - psycopg2 # For connecting to PostgreSQL
  - pytest   # For running tests
  - pyyaml   # For working with YAML files
  - jupyterlab # Assuming you use Jupyter, add if needed
  - xarray
  - rioxarray

  # --- The NEW packages you want to install ---
  - minisom
  - spopt