# Test configuration for pipeline integrity test
# Only process one dataset to verify the pipeline works end-to-end

datasets:
  target_datasets:
    - name: 'plants-richness'
      path: '/home/jason/geo/data/richness_maps/daru-plants-richness.tif'
      path_key: 'plants_richness'
      data_type: 'richness_data'
      band_name: 'plants_richness'
      enabled: true
    - name: 'terrestrial-richness'
      path: '/home/jason/geo/data/richness_maps/iucn-terrestrial-richness.tif'
      path_key: 'terrestrial_richness'
      data_type: 'richness_data'
      band_name: 'terrestrial_richness'
      enabled: false  # Disable this dataset for testing

# Use a smaller target resolution for faster processing
resampling:
  target_resolution: 0.1  # Larger resolution = less data to process
  target_crs: 'EPSG:4326'
  strategies:
    richness_data: 'sum'
  chunk_size: 500
  validate_output: true
  cache_resampled: true
  preserve_sum: true

# Limit processing bounds for testing
processing_bounds:
  enabled: true
  west: -10
  south: -10
  east: 10
  north: 10

# Test mode settings
testing:
  enabled: true
  cleanup_after_test: false  # Keep data for inspection